from __future__ import print_function, absolute_import

from .reid_loaders import ReIDLoaders
from .incremental_reid_loaders import IncrementalReIDLoaders
from .customed_loaders import CustomedLoaders
from .transforms2 import RandomErasing
from .incremental_datasets import IncrementalReIDDataSet, Incremental_combine_train_samples, Incremental_combine_test_samples